use_frameworks!

pod 'SDWebImage', '~> 3.7.5'
pod 'MJRefresh', '~> 3.1.0'
pod 'RxSwift', '~> 2.2.0'
pod 'RxCocoa' , '~> 2.2.0'
pod 'RxAlamofire', '~> 2.2'
pod 'Alamofire', '~> 3.2.1'
pod 'SwiftyJSON', '~> 2.3.2'